name: Merge main to staging

on:
  push:
    branches:
      - main

jobs:
  main-to-staging:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.BOT_PERSONAL_ACCESS_TOKEN }}
      - name: Setup Github Cli
        shell: bash
        run: |
          curl -L -o gh.deb https://github.com/cli/cli/releases/download/v2.14.7/gh_2.14.7_linux_amd64.deb && sudo dpkg -i gh.deb
      - name: Create PR from main to staging
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.BOT_PERSONAL_ACCESS_TOKEN }}
        run: |
          git config user.name two-inc-bot
          git config user.email bot@two.inc
          git pull
          git checkout staging
          if git merge main; then
            # no merge conflict, create a PR and merge automatically
            git push
          else
            # merge conflict detected, create a PR and assign reviewers
            git merge --abort
            git checkout main -b merge-main
            git push --force --set-upstream origin merge-main
            gh pr create --base staging --title "Merge main into staging" --body="" --reviewer two-inc/core
          fi
